# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout_2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from pymongo import MongoClient
import threading
import pyqtgraph as pg
from time import mktime
from datetime import datetime, timedelta
import time
import numpy as np
from pyqtgraph.Point import Point


vesselArray = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64']

#initializing database connection and information

client = MongoClient('mongodb://localhost:27017')
db = client.testdb
collection1 = db.co2

#initializing timer and data lists

dataList = []
timeList = []
timers = []
timers1 = []

#initializing collection in database

db_data = collection1.find()


#To plot time on the x axis.
class DateAxisItem(pg.AxisItem):
    """
    A tool that provides a date-time aware axis. It is implemented as an
    AxisItem that interpretes positions as unix timestamps (i.e. seconds
    since 1970).
    The labels and the tick positions are dynamically adjusted depending
    on the range.
    It provides a  :meth:`attachToPlotItem` method to add it to a given
    PlotItem
    """
    
    # Max width in pixels reserved for each label in axis
    _pxLabelWidth = 80

    def __init__(self, *args, **kwargs):
        pg.AxisItem.__init__(self, *args, **kwargs)
        self._oldAxis = None

    def tickValues(self, minVal, maxVal, size):
        """
        Reimplemented from PlotItem to adjust to the range and to force
        the ticks at "round" positions in the context of time units instead of
        rounding in a decimal base
        """

        maxMajSteps = int(size/self._pxLabelWidth)

        dt1 = datetime.fromtimestamp(minVal)
        dt2 = datetime.fromtimestamp(maxVal)

        dx = maxVal - minVal
        majticks = []

        if dx > 63072001:  # 3600s*24*(365+366) = 2 years (count leap year)
            d = timedelta(days=366)
            for y in range(dt1.year + 1, dt2.year):
                dt = datetime(year=y, month=1, day=1)
                majticks.append(mktime(dt.timetuple()))

        elif dx > 5270400:  # 3600s*24*61 = 61 days
            d = timedelta(days=31)
            dt = dt1.replace(day=1, hour=0, minute=0,
                             second=0, microsecond=0) + d
            while dt < dt2:
                # make sure that we are on day 1 (even if always sum 31 days)
                dt = dt.replace(day=1)
                majticks.append(mktime(dt.timetuple()))
                dt += d

        elif dx > 172800:  # 3600s24*2 = 2 days
            d = timedelta(days=1)
            dt = dt1.replace(hour=0, minute=0, second=0, microsecond=0) + d
            while dt < dt2:
                majticks.append(mktime(dt.timetuple()))
                dt += d

        elif dx > 7200:  # 3600s*2 = 2hours
            d = timedelta(hours=1)
            dt = dt1.replace(minute=0, second=0, microsecond=0) + d
            while dt < dt2:
                majticks.append(mktime(dt.timetuple()))
                dt += d

        elif dx > 1200:  # 60s*20 = 20 minutes
            d = timedelta(minutes=10)
            dt = dt1.replace(minute=(dt1.minute // 10) * 10,
                             second=0, microsecond=0) + d
            while dt < dt2:
                majticks.append(mktime(dt.timetuple()))
                dt += d

        elif dx > 120:  # 60s*2 = 2 minutes
            d = timedelta(minutes=1)
            dt = dt1.replace(second=0, microsecond=0) + d
            while dt < dt2:
                majticks.append(mktime(dt.timetuple()))
                dt += d

        elif dx > 20:  # 20s
            d = timedelta(seconds=10)
            dt = dt1.replace(second=(dt1.second // 10) * 10, microsecond=0) + d
            while dt < dt2:
                majticks.append(mktime(dt.timetuple()))
                dt += d

        elif dx > 2:  # 2s
            d = timedelta(seconds=1)
            majticks = range(int(minVal), int(maxVal))

        else:  # <2s , use standard implementation from parent
            return pg.AxisItem.tickValues(self, minVal, maxVal, size)

        L = len(majticks)
        if L > maxMajSteps:
            majticks = majticks[::int(np.ceil(float(L) / maxMajSteps))]

        return [(d.total_seconds(), majticks)]

    def tickStrings(self, values, scale, spacing):
        """Reimplemented from PlotItem to adjust to the range"""
        ret = []
        if not values:
            return []

        if spacing >= 31622400:  # 366 days
            fmt = "%Y"

        elif spacing >= 2678400:  # 31 days
            fmt = "%Y %b"

        elif spacing >= 86400:  # = 1 day
            fmt = "%b/%d"

        elif spacing >= 3600:  # 1 h
            fmt = "%b/%d-%Hh"

        elif spacing >= 60:  # 1 m
            fmt = "%H:%M"

        elif spacing >= 1:  # 1s
            fmt = "%H:%M:%S"

        else:
            # less than 2s (show microseconds)
            # fmt = '%S.%f"'
            fmt = '[+%fms]'  # explicitly relative to last second

        for x in values:
            try:
                t = datetime.fromtimestamp(x)
                ret.append(t.strftime(fmt))
            except ValueError:  # Windows can't handle dates before 1970
                ret.append('')

        return ret

    def attachToPlotItem(self, plotItem):
        """Add this axis to the given PlotItem
        :param plotItem: (PlotItem)
        """
        self.setParentItem(plotItem)
        viewBox = plotItem.getViewBox()
        self.linkToView(viewBox)
        self._oldAxis = plotItem.axes[self.orientation]['item']
        self._oldAxis.hide()
        plotItem.axes[self.orientation]['item'] = self
        pos = plotItem.axes[self.orientation]['pos']
        plotItem.layout.addItem(self, *pos)
        self.setZValue(-1000)

    def detachFromPlotItem(self):
        """Remove this axis from its attached PlotItem
        (not yet implemented)
        """
        raise NotImplementedError()  # TODO


class Ui_MainWindow(object): 
        def exitButton(self, MainWindow):
                sys.exit()

        def startButton(self, MainWindow):
                self.Experiment_Name_input = self.Experiment_Name_TextEdit.toPlainText()
                self.Sampling_Frequency_Day_input = self.Sampling_Frequency_Day_TextEdit.toPlainText()
                self.Glucose_Setpoint_input = self.Glucose_Setpoint_TextEdit.toPlainText()
                self.Nitrite_Setpoint_input = self.Nitrite_Setpoint_TextEdit.toPlainText()
                self.Nitrite_Max_Diff_input = self.Nitrite_Max_Diff_TextEdit.toPlainText()
                self.Glucose_Max_Diff_input = self.Glucose_Max_Diff_TextEdit.toPlainText()
                self.Source_Nitrite_Concentration_TextEdit = self.Source_Nitrite_Concentration_TextEdit.toPlainText()
                self.Source_Glucose_Concentration_TextEdit = self.Source_Glucose_Concentration_TextEdit.toPlainText()
                self.Number_of_Vessels_Dropdown_input = str(self.Number_of_Vessels_Dropdown.currentText())
                self.Libelium_Dropdown_input = str(self.Libelium_Dropdown.currentText())
                self.Nitrite_Dropdown_input = str(self.Nitrite_Dropdown.currentText())
                self.Nitrate_Dropdown_input = str(self.Nitrate_Dropdown.currentText())
                self.Ammonium_Dropdown_input = str(self.Ammonium_Dropdown.currentText())
                self.pH_Dropdown_input = str(self.pH_Dropdown.currentText())
                self.Relays_Dropdown_input = str(self.Relays_Dropdown.currentText())
                self.Delivery_Servos_Dropdown_input = str(self.Delivery_Servos_Dropdown.currentText())
                self.Sampling_Servos_Dropdown_input = str(self.Sampling_Servos_Dropdown.currentText())
                self.CO2_Dropdown_input = str(self.CO2_Dropdown.currentText())
                self.DO_Dropdown_input = str(self.DO_Dropdown.currentText())
                self.Liquid_Flow_Meter_Dropdown_input = str(self.Liquid_Flow_Meter_Dropdown.currentText())
                self.Cell_Counter_Dropdown_input = str(self.Cell_Counter_Dropdown.currentText())
                self.Gas_Flow_Meter_Dropdown_input = str(self.Gas_Flow_Meter_Dropdown.currentText())
                print(self.Experiment_Name_input)
                print(self.Sampling_Frequency_Day_input)
                print(self.Glucose_Setpoint_input)
                print(self.Glucose_Max_Diff_input)
                print(self.Source_Glucose_Concentration_TextEdit)

                

#user_input = Experiment_Name_TextEdit, Number_of_Vessels_Dropdown, Sampling_Frequency_Day_TextEdit, Glucose_Setpoint_TextEdit, Nitrite_Setpoint_TextEdit, Glucose_Max_Diff_TextEdit, Nitrite_Max_Diff_TextEdit,

                #Dropdown menus for selecting COM Ports

                #Libelium_Dropdown, Nitrite_Dropdown, Nitrate_Dropdown, Ammonium_Dropdown, pH_Dropdown, Relays_Dropdown, Delivery_Servos_Dropdown, Sampling_Servos_Dropdown, CO2_Dropdown, DO_Dropdown, Liquid_Flow_Meter_Dropdown,
                #Cell_Counter_Dropdown, Gas_Flow_Meter_Dropdown
        def update(self):
                self.updateDOList = []
                self.updateGlucoseList = []
                self.updateCO2List = []
                self.updateNitriteList = []
                self.updateNitrateList = []
                self.updatepHList = []
                self.updateAmmoniumList = []
                self.updateYList = []
                self.updateTList = []
                self.vesselList = []
                self.experimentList = []

                time_init = 0
                timebetweenreads = 6
                #Grabs data from current experiment from a specific vessel
                #Replace 'Vessel 1'with user input from dropdown menu you can use an array
                query = {'$and':[{'Vessel':'Vessel 1'},{'Experiment': 'Experiment 1'}]}
                #Grabs data from current experiment from all vessels
                queryAllVes = {'Experiment': 'Test2'}
                self.db_vesData = list(collection1.find(query))
                self.db_allData = list(collection1.find(queryAllVes))
                #print(db_data)
                for x in self.db_allData:
                        self.updateYList.append(x['ComputerTime'])
                        self.updateCO2List.append(x['CO2 Level'])
                        #print(self.updateYList)
                        self.updateTList.append(x['Time'])
                        self.vesselList.append(x['Vessel'])
                        self.updateGlucoseList.append(x['Glucose Level'])
                        self.experimentList.append(x['Experiment'])
                        self.updateDOList.append(x['DO Level'])
                        self.updatepHList.append(x['pH Level'])
                        self.updateNitriteList.append(x['Nitrite Level'])
                        self.updateNitrateList.append(x['Nitrate Level'])
                        self.updateAmmoniumList.append(x['Ammonium Level'])
                        
                #updateYList.append(x['Time'])
                #timeList.append(time_init)
                #time_init = time_init + timebetweenreads
                #updateYList = np.arange(0, 6*len(updateXList), 6)
                self.lengthoflist = len(self.updateYList)
                print(self.lengthoflist)
                
        #plot function:
        def plot(self):
                if self.View_Culture_Status_TabWidget.isTabEnabled(0) == True:
                        for i in range(64):
                                self.Glucose_All_Vessels_PlotWidget.plot(self.updateYList,self.updateGlucoseList,title = "All Glucose Data", pen=(i,64))
                if self.View_Culture_Status_TabWidget.isTabEnabled(1) == True:
                        for i in range(64):
                                self.Nitrite_All_Vessels_PlotWidget.plot(self.updateYList,self.updateNitriteList,title = "All Glucose Data", pen=(i,64))
                                #print(self.updateGlucoseList)
        
        #builds lists and plots
        #make tab button call plot function on click(try .currentIndex() function to find correct tab and then plot that tab data onto PlotWidget)
        #whenever using while loop, call threading function(plot function)
        #add pause button for experiment.

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(763, 591)
                MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.Main_TabWidget = QtWidgets.QTabWidget(self.centralwidget)
                self.Main_TabWidget.setGeometry(QtCore.QRect(0, 0, 761, 561))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.Main_TabWidget.sizePolicy().hasHeightForWidth())
                self.Main_TabWidget.setSizePolicy(sizePolicy)
                self.Main_TabWidget.setStyleSheet("QTabBar::tab { height: 45px; width: 130px; }\n"
        "")
                self.Main_TabWidget.setObjectName("Main_TabWidget")
                self.tab_11 = QtWidgets.QWidget()
                self.tab_11.setObjectName("tab_11")
                self.Experiment_Parameters_Label = QtWidgets.QLabel(self.tab_11)
                self.Experiment_Parameters_Label.setGeometry(QtCore.QRect(300, 20, 171, 21))
                font = QtGui.QFont()
                font.setFamily("MS Sans Serif")
                font.setPointSize(12)
                font.setBold(False)
                font.setItalic(False)
                font.setUnderline(True)
                font.setWeight(50)
                self.Experiment_Parameters_Label.setFont(font)
                self.Experiment_Parameters_Label.setStyleSheet("font: 12pt \"MS Sans Serif\";\n"
        "color: rgb(255, 255, 255);")
                self.Experiment_Parameters_Label.setObjectName("Experiment_Parameters_Label")
                self.Experiment_Name_Label = QtWidgets.QLabel(self.tab_11)
                self.Experiment_Name_Label.setGeometry(QtCore.QRect(20, 80, 91, 20))
                self.Experiment_Name_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Experiment_Name_Label.setObjectName("Experiment_Name_Label")
                self.Number_of_Vessels_Label = QtWidgets.QLabel(self.tab_11)
                self.Number_of_Vessels_Label.setGeometry(QtCore.QRect(20, 120, 91, 20))
                self.Number_of_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Number_of_Vessels_Label.setObjectName("Number_of_Vessels_Label")
                self.Sampling_Frequency_Day_Label = QtWidgets.QLabel(self.tab_11)
                self.Sampling_Frequency_Day_Label.setGeometry(QtCore.QRect(10, 160, 121, 20))
                self.Sampling_Frequency_Day_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Sampling_Frequency_Day_Label.setObjectName("Sampling_Frequency_Day_Label")
                self.Glucose_Setpoint_Label = QtWidgets.QLabel(self.tab_11)
                self.Glucose_Setpoint_Label.setGeometry(QtCore.QRect(20, 200, 111, 20))
                self.Glucose_Setpoint_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Glucose_Setpoint_Label.setObjectName("Glucose_Setpoint_Label")
                self.Nitrite_Setpoint_Label = QtWidgets.QLabel(self.tab_11)
                self.Nitrite_Setpoint_Label.setGeometry(QtCore.QRect(20, 240, 101, 21))
                self.Nitrite_Setpoint_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Nitrite_Setpoint_Label.setObjectName("Nitrite_Setpoint_Label")
                self.Experiment_Name_TextEdit = QtWidgets.QPlainTextEdit(self.tab_11)
                self.Experiment_Name_TextEdit.setGeometry(QtCore.QRect(140, 70, 121, 31))
                self.Experiment_Name_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Experiment_Name_TextEdit.setObjectName("Experiment_Name_TextEdit")
                self.Source_Nitrite_Concentration_TextEdit = QtWidgets.QPlainTextEdit(self.tab_11)
                self.Source_Nitrite_Concentration_TextEdit.setGeometry(QtCore.QRect(450, 110, 121, 31))
                self.Source_Nitrite_Concentration_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Source_Nitrite_Concentration_TextEdit.setObjectName("Source_Nitrite_Concentration_TextEdit")
                self.Sampling_Frequency_Day_TextEdit = QtWidgets.QPlainTextEdit(self.tab_11)
                self.Sampling_Frequency_Day_TextEdit.setGeometry(QtCore.QRect(140, 150, 121, 31))
                self.Sampling_Frequency_Day_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Sampling_Frequency_Day_TextEdit.setObjectName("Sampling_Frequency_Day_TextEdit")
                self.Glucose_Setpoint_TextEdit = QtWidgets.QPlainTextEdit(self.tab_11)
                self.Glucose_Setpoint_TextEdit.setGeometry(QtCore.QRect(140, 190, 121, 31))
                self.Glucose_Setpoint_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Glucose_Setpoint_TextEdit.setObjectName("Glucose_Setpoint_TextEdit")
                self.Nitrite_Setpoint_TextEdit = QtWidgets.QPlainTextEdit(self.tab_11)
                self.Nitrite_Setpoint_TextEdit.setGeometry(QtCore.QRect(140, 230, 121, 31))
                self.Nitrite_Setpoint_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Nitrite_Setpoint_TextEdit.setObjectName("Nitrite_Setpoint_TextEdit")
                self.Glucose_Max_Diff_Label = QtWidgets.QLabel(self.tab_11)
                self.Glucose_Max_Diff_Label.setGeometry(QtCore.QRect(310, 190, 121, 20))
                self.Glucose_Max_Diff_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Glucose_Max_Diff_Label.setObjectName("Glucose_Max_Diff_Label")
                self.Nitrite_Max_Diff_Label = QtWidgets.QLabel(self.tab_11)
                self.Nitrite_Max_Diff_Label.setGeometry(QtCore.QRect(320, 230, 111, 20))
                self.Nitrite_Max_Diff_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Nitrite_Max_Diff_Label.setObjectName("Nitrite_Max_Diff_Label")
                self.Source_Glucose_Concentration_Label = QtWidgets.QLabel(self.tab_11)
                self.Source_Glucose_Concentration_Label.setGeometry(QtCore.QRect(270, 150, 181, 20))
                self.Source_Glucose_Concentration_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Source_Glucose_Concentration_Label.setObjectName("Source_Glucose_Concentration_Label")
                self.Source_Nitrite_Concentration_Label = QtWidgets.QLabel(self.tab_11)
                self.Source_Nitrite_Concentration_Label.setGeometry(QtCore.QRect(270, 110, 171, 20))
                self.Source_Nitrite_Concentration_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Source_Nitrite_Concentration_Label.setObjectName("Source_Nitrite_Concentration_Label")
                self.Source_Glucose_Concentration_TextEdit = QtWidgets.QPlainTextEdit(self.tab_11)
                self.Source_Glucose_Concentration_TextEdit.setGeometry(QtCore.QRect(450, 150, 121, 31))
                self.Source_Glucose_Concentration_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Source_Glucose_Concentration_TextEdit.setObjectName("Source_Glucose_Concentration_TextEdit")
                self.Glucose_Max_Diff_TextEdit = QtWidgets.QPlainTextEdit(self.tab_11)
                self.Glucose_Max_Diff_TextEdit.setGeometry(QtCore.QRect(450, 190, 121, 31))
                self.Glucose_Max_Diff_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Glucose_Max_Diff_TextEdit.setObjectName("Glucose_Max_Diff_TextEdit")
                self.Nitrite_Max_Diff_TextEdit = QtWidgets.QPlainTextEdit(self.tab_11)
                self.Nitrite_Max_Diff_TextEdit.setGeometry(QtCore.QRect(450, 230, 121, 31))
                self.Nitrite_Max_Diff_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Nitrite_Max_Diff_TextEdit.setObjectName("Nitrite_Max_Diff_TextEdit")
                self.Number_of_Vessels_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Number_of_Vessels_Dropdown.setGeometry(QtCore.QRect(140, 111, 121, 31))
                self.Number_of_Vessels_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Number_of_Vessels_Dropdown.setObjectName("Number_of_Vessels_Dropdown")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                self.Number_of_Vessels_Dropdown.addItem("")
                #gives start experiment button functionality
                
                self.Start_Experiment_Button = QtWidgets.QPushButton(self.tab_11)
                self.Start_Experiment_Button.setGeometry(QtCore.QRect(600, 90, 131, 71))
                self.Start_Experiment_Button.setStyleSheet("background-color: rgb(0, 170, 0);\n"
        "font: 10pt \"MS Sans Serif\";")
                self.Start_Experiment_Button.setObjectName("Start_Experiment_Button")
                self.Start_Experiment_Button.clicked.connect(self.startButton)
                #gives end experiment button functionality
                
                self.End_Experiment_Button = QtWidgets.QPushButton(self.tab_11)
                self.End_Experiment_Button.setGeometry(QtCore.QRect(600, 180, 131, 71))
                self.End_Experiment_Button.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        "font: 10pt \"MS Sans Serif\";")
                self.End_Experiment_Button.setObjectName("End_Experiment_Button")
                self.End_Experiment_Button.clicked.connect(self.exitButton)
                self.Assign_COM_Ports_Label = QtWidgets.QLabel(self.tab_11)
                self.Assign_COM_Ports_Label.setGeometry(QtCore.QRect(320, 290, 131, 21))
                font = QtGui.QFont()
                font.setFamily("MS Sans Serif")
                font.setPointSize(12)
                font.setBold(False)
                font.setItalic(False)
                font.setUnderline(True)
                font.setWeight(50)
                self.Assign_COM_Ports_Label.setFont(font)
                self.Assign_COM_Ports_Label.setStyleSheet("font: 12pt \"MS Sans Serif\";\n"
        "color: rgb(255, 255, 255);")
                self.Assign_COM_Ports_Label.setObjectName("Assign_COM_Ports_Label")
                self.Libelium_Label = QtWidgets.QLabel(self.tab_11)
                self.Libelium_Label.setGeometry(QtCore.QRect(30, 320, 51, 21))
                self.Libelium_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Libelium_Label.setObjectName("Libelium_Label")
                self.Nitrite_Label = QtWidgets.QLabel(self.tab_11)
                self.Nitrite_Label.setGeometry(QtCore.QRect(190, 320, 51, 21))
                self.Nitrite_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Nitrite_Label.setObjectName("Nitrite_Label")
                self.Nitrate_Label = QtWidgets.QLabel(self.tab_11)
                self.Nitrate_Label.setGeometry(QtCore.QRect(350, 320, 51, 21))
                self.Nitrate_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Nitrate_Label.setObjectName("Nitrate_Label")
                self.Ammonium_Label = QtWidgets.QLabel(self.tab_11)
                self.Ammonium_Label.setGeometry(QtCore.QRect(500, 320, 61, 21))
                self.Ammonium_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Ammonium_Label.setObjectName("Ammonium_Label")
                self.pH_Label = QtWidgets.QLabel(self.tab_11)
                self.pH_Label.setGeometry(QtCore.QRect(650, 320, 21, 21))
                self.pH_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.pH_Label.setObjectName("pH_Label")
                self.Relays_Label = QtWidgets.QLabel(self.tab_11)
                self.Relays_Label.setGeometry(QtCore.QRect(60, 370, 51, 21))
                self.Relays_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Relays_Label.setObjectName("Relays_Label")
                self.Delivery_Servos_Label = QtWidgets.QLabel(self.tab_11)
                self.Delivery_Servos_Label.setGeometry(QtCore.QRect(30, 410, 81, 21))
                self.Delivery_Servos_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Delivery_Servos_Label.setObjectName("Delivery_Servos_Label")
                self.Sampling_Servos_Label = QtWidgets.QLabel(self.tab_11)
                self.Sampling_Servos_Label.setGeometry(QtCore.QRect(30, 450, 81, 21))
                self.Sampling_Servos_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Sampling_Servos_Label.setObjectName("Sampling_Servos_Label")
                self.CO2_label = QtWidgets.QLabel(self.tab_11)
                self.CO2_label.setGeometry(QtCore.QRect(290, 370, 31, 21))
                self.CO2_label.setStyleSheet("color: rgb(255, 255, 255);")
                self.CO2_label.setObjectName("CO2_label")
                self.DO_Label = QtWidgets.QLabel(self.tab_11)
                self.DO_Label.setGeometry(QtCore.QRect(290, 410, 21, 21))
                self.DO_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.DO_Label.setObjectName("DO_Label")
                self.Liquid_Flow_Meter_Label = QtWidgets.QLabel(self.tab_11)
                self.Liquid_Flow_Meter_Label.setGeometry(QtCore.QRect(240, 450, 91, 21))
                self.Liquid_Flow_Meter_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Liquid_Flow_Meter_Label.setObjectName("Liquid_Flow_Meter_Label")
                self.Cell_Counter_Label = QtWidgets.QLabel(self.tab_11)
                self.Cell_Counter_Label.setGeometry(QtCore.QRect(500, 370, 61, 21))
                self.Cell_Counter_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Cell_Counter_Label.setObjectName("Cell_Counter_Label")
                self.Gas_Flow_Meter_Label = QtWidgets.QLabel(self.tab_11)
                self.Gas_Flow_Meter_Label.setGeometry(QtCore.QRect(480, 410, 81, 21))
                self.Gas_Flow_Meter_Label.setStyleSheet("color: rgb(255, 255, 255);")
                self.Gas_Flow_Meter_Label.setObjectName("Gas_Flow_Meter_Label")
                self.Libelium_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Libelium_Dropdown.setGeometry(QtCore.QRect(90, 320, 69, 22))
                self.Libelium_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Libelium_Dropdown.setObjectName("Libelium_Dropdown")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Libelium_Dropdown.addItem("")
                self.Nitrite_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Nitrite_Dropdown.setGeometry(QtCore.QRect(240, 320, 69, 22))
                self.Nitrite_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Nitrite_Dropdown.setObjectName("Nitrite_Dropdown")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrite_Dropdown.addItem("")
                self.Nitrate_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Nitrate_Dropdown.setGeometry(QtCore.QRect(400, 320, 69, 22))
                self.Nitrate_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Nitrate_Dropdown.setObjectName("Nitrate_Dropdown")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Nitrate_Dropdown.addItem("")
                self.Ammonium_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Ammonium_Dropdown.setGeometry(QtCore.QRect(560, 320, 69, 22))
                self.Ammonium_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Ammonium_Dropdown.setObjectName("Ammonium_Dropdown")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.Ammonium_Dropdown.addItem("")
                self.pH_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.pH_Dropdown.setGeometry(QtCore.QRect(680, 320, 69, 22))
                self.pH_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.pH_Dropdown.setObjectName("pH_Dropdown")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.pH_Dropdown.addItem("")
                self.Relays_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Relays_Dropdown.setGeometry(QtCore.QRect(120, 370, 69, 22))
                self.Relays_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Relays_Dropdown.setObjectName("Relays_Dropdown")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Relays_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Delivery_Servos_Dropdown.setGeometry(QtCore.QRect(120, 410, 69, 22))
                self.Delivery_Servos_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Delivery_Servos_Dropdown.setObjectName("Delivery_Servos_Dropdown")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Delivery_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Sampling_Servos_Dropdown.setGeometry(QtCore.QRect(120, 450, 69, 22))
                self.Sampling_Servos_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Sampling_Servos_Dropdown.setObjectName("Sampling_Servos_Dropdown")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.Sampling_Servos_Dropdown.addItem("")
                self.CO2_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.CO2_Dropdown.setGeometry(QtCore.QRect(330, 370, 69, 22))
                self.CO2_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.CO2_Dropdown.setObjectName("CO2_Dropdown")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.CO2_Dropdown.addItem("")
                self.DO_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.DO_Dropdown.setGeometry(QtCore.QRect(330, 410, 69, 22))
                self.DO_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.DO_Dropdown.setObjectName("DO_Dropdown")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.DO_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Liquid_Flow_Meter_Dropdown.setGeometry(QtCore.QRect(330, 450, 69, 22))
                self.Liquid_Flow_Meter_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Liquid_Flow_Meter_Dropdown.setObjectName("Liquid_Flow_Meter_Dropdown")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Liquid_Flow_Meter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Cell_Counter_Dropdown.setGeometry(QtCore.QRect(570, 370, 69, 22))
                self.Cell_Counter_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Cell_Counter_Dropdown.setObjectName("Cell_Counter_Dropdown")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Cell_Counter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown = QtWidgets.QComboBox(self.tab_11)
                self.Gas_Flow_Meter_Dropdown.setGeometry(QtCore.QRect(570, 410, 69, 22))
                self.Gas_Flow_Meter_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Gas_Flow_Meter_Dropdown.setObjectName("Gas_Flow_Meter_Dropdown")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Gas_Flow_Meter_Dropdown.addItem("")
                self.Main_TabWidget.addTab(self.tab_11, "")
                self.tab_12 = QtWidgets.QWidget()
                self.tab_12.setObjectName("tab_12")
                self.CO2_Concentration_Label = QtWidgets.QLabel(self.tab_12)
                self.CO2_Concentration_Label.setGeometry(QtCore.QRect(300, 30, 141, 21))
                font = QtGui.QFont()
                font.setFamily("MS Sans Serif")
                font.setPointSize(12)
                font.setBold(False)
                font.setItalic(False)
                font.setUnderline(True)
                font.setWeight(50)
                self.CO2_Concentration_Label.setFont(font)
                self.CO2_Concentration_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 12pt \"MS Sans Serif\";")
                self.CO2_Concentration_Label.setObjectName("CO2_Concentration_Label")
                self.Gas_Flow_Rate_Label = QtWidgets.QLabel(self.tab_12)
                self.Gas_Flow_Rate_Label.setGeometry(QtCore.QRect(320, 260, 111, 21))
                font = QtGui.QFont()
                font.setFamily("MS Sans Serif")
                font.setPointSize(12)
                font.setBold(False)
                font.setItalic(False)
                font.setUnderline(True)
                font.setWeight(50)
                self.Gas_Flow_Rate_Label.setFont(font)
                self.Gas_Flow_Rate_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 12pt \"MS Sans Serif\";")
                self.Gas_Flow_Rate_Label.setObjectName("Gas_Flow_Rate_Label")
                self.CO2_Concentration_PlotWidget = PlotWidget(self.tab_12)
                self.CO2_Concentration_PlotWidget.setGeometry(QtCore.QRect(140, 60, 461, 201))
                self.CO2_Concentration_PlotWidget.setObjectName("CO2_Concentration_PlotWidget")
                self.Gas_Flow_Rate_PlotWidget = PlotWidget(self.tab_12)
                self.Gas_Flow_Rate_PlotWidget.setGeometry(QtCore.QRect(140, 290, 461, 201))
                self.Gas_Flow_Rate_PlotWidget.setObjectName("Gas_Flow_Rate_PlotWidget")
                self.Main_TabWidget.addTab(self.tab_12, "")
                self.tab_13 = QtWidgets.QWidget()
                self.tab_13.setObjectName("tab_13")
                self.View_Culture_Status_TabWidget = QtWidgets.QTabWidget(self.tab_13)
                self.View_Culture_Status_TabWidget.setGeometry(QtCore.QRect(0, 0, 761, 511))
                self.View_Culture_Status_TabWidget.setStyleSheet("QTabBar::tab { height: 45px; width: 110px; }")
                self.View_Culture_Status_TabWidget.setObjectName("View_Culture_Status_TabWidget")
                self.tab = QtWidgets.QWidget()
                self.tab.setObjectName("tab")
                self.Glucose_Select_Vessels_Label = QtWidgets.QLabel(self.tab)
                self.Glucose_Select_Vessels_Label.setGeometry(QtCore.QRect(60, 90, 131, 16))
                self.Glucose_Select_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Glucose_Select_Vessels_Label.setObjectName("Glucose_Select_Vessels_Label")
                self.Glucose_Selection_Label = QtWidgets.QLabel(self.tab)
                self.Glucose_Selection_Label.setGeometry(QtCore.QRect(440, 50, 91, 16))
                self.Glucose_Selection_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Glucose_Selection_Label.setObjectName("Glucose_Selection_Label")
                self.Glucose_All_Vessels_Label = QtWidgets.QLabel(self.tab)
                self.Glucose_All_Vessels_Label.setGeometry(QtCore.QRect(300, 250, 101, 16))
                self.Glucose_All_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                date_axis = DateAxisItem(orientation = 'bottom')
                self.Glucose_All_Vessels_Label.setObjectName("Glucose_All_Vessels_Label")
                self.Glucose_Select_Vessels_Dropdown = QtWidgets.QComboBox(self.tab)
                self.Glucose_Select_Vessels_Dropdown.setGeometry(QtCore.QRect(90, 140, 69, 22))
                self.Glucose_Select_Vessels_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Glucose_Select_Vessels_Dropdown.setObjectName("Glucose_Select_Vessels_Dropdown")
                self.Glucose_All_Vessels_PlotWidget = PlotWidget(self.tab, axisItems = {'bottom': date_axis})
                self.Glucose_All_Vessels_PlotWidget.setGeometry(QtCore.QRect(220, 270, 281, 171))
                self.Glucose_All_Vessels_PlotWidget.setObjectName("Glucose_All_Vessels_PlotWidget")
                self.Glucose_Selection_PlotWidget = PlotWidget(self.tab)
                self.Glucose_Selection_PlotWidget.setGeometry(QtCore.QRect(350, 70, 281, 171))
                self.Glucose_Selection_PlotWidget.setObjectName("Glucose_Selection_PlotWidget")
                self.View_Culture_Status_TabWidget.addTab(self.tab, "")
                self.tab_3 = QtWidgets.QWidget()
                self.tab_3.setObjectName("tab_3")
                self.Nitrite_All_Vessels_Label = QtWidgets.QLabel(self.tab_3)
                self.Nitrite_All_Vessels_Label.setGeometry(QtCore.QRect(300, 250, 101, 16))
                self.Nitrite_All_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Nitrite_All_Vessels_Label.setObjectName("Nitrite_All_Vessels_Label")
                self.Nitrite_Select_Vessels_Dropdown = QtWidgets.QComboBox(self.tab_3)
                self.Nitrite_Select_Vessels_Dropdown.setGeometry(QtCore.QRect(90, 140, 69, 22))
                self.Nitrite_Select_Vessels_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Nitrite_Select_Vessels_Dropdown.setObjectName("Nitrite_Select_Vessels_Dropdown")
                self.Nitrite_Select_Vessels_Label = QtWidgets.QLabel(self.tab_3)
                self.Nitrite_Select_Vessels_Label.setGeometry(QtCore.QRect(60, 90, 131, 16))
                self.Nitrite_Select_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Nitrite_Select_Vessels_Label.setObjectName("Nitrite_Select_Vessels_Label")
                self.Nitrite_Selection_Label = QtWidgets.QLabel(self.tab_3)
                self.Nitrite_Selection_Label.setGeometry(QtCore.QRect(440, 50, 91, 16))
                self.Nitrite_Selection_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Nitrite_Selection_Label.setObjectName("Nitrite_Selection_Label")
                self.Nitrite_All_Vessels_PlotWidget = PlotWidget(self.tab_3)
                self.Nitrite_All_Vessels_PlotWidget.setGeometry(QtCore.QRect(220, 270, 281, 171))
                self.Nitrite_All_Vessels_PlotWidget.setObjectName("Nitrite_All_Vessels_PlotWidget")
                self.Nitrite_Selection_PlotWidget = PlotWidget(self.tab_3)
                self.Nitrite_Selection_PlotWidget.setGeometry(QtCore.QRect(350, 70, 281, 171))
                self.Nitrite_Selection_PlotWidget.setObjectName("Nitrite_Selection_PlotWidget")
                self.View_Culture_Status_TabWidget.addTab(self.tab_3, "")
                self.tab_4 = QtWidgets.QWidget()
                self.tab_4.setObjectName("tab_4")
                self.Nitrate_All_Vessels_Label = QtWidgets.QLabel(self.tab_4)
                self.Nitrate_All_Vessels_Label.setGeometry(QtCore.QRect(300, 250, 101, 16))
                self.Nitrate_All_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Nitrate_All_Vessels_Label.setObjectName("Nitrate_All_Vessels_Label")
                self.Nitrate_Select_Vessels_Dropdown = QtWidgets.QComboBox(self.tab_4)
                self.Nitrate_Select_Vessels_Dropdown.setGeometry(QtCore.QRect(90, 140, 69, 22))
                self.Nitrate_Select_Vessels_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Nitrate_Select_Vessels_Dropdown.setObjectName("Nitrate_Select_Vessels_Dropdown")
                self.Nitrate_Select_Vessels_Label = QtWidgets.QLabel(self.tab_4)
                self.Nitrate_Select_Vessels_Label.setGeometry(QtCore.QRect(60, 90, 131, 16))
                self.Nitrate_Select_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Nitrate_Select_Vessels_Label.setObjectName("Nitrate_Select_Vessels_Label")
                self.Nitrate_Selection_Label = QtWidgets.QLabel(self.tab_4)
                self.Nitrate_Selection_Label.setGeometry(QtCore.QRect(440, 50, 91, 16))
                self.Nitrate_Selection_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Nitrate_Selection_Label.setObjectName("Nitrate_Selection_Label")
                self.Nitrate_All_Vessels_PlotWidget = PlotWidget(self.tab_4)
                self.Nitrate_All_Vessels_PlotWidget.setGeometry(QtCore.QRect(220, 270, 281, 171))
                self.Nitrate_All_Vessels_PlotWidget.setObjectName("Nitrate_All_Vessels_PlotWidget")
                self.Nitrate_Selection_PlotWidget = PlotWidget(self.tab_4)
                self.Nitrate_Selection_PlotWidget.setGeometry(QtCore.QRect(350, 70, 281, 171))
                self.Nitrate_Selection_PlotWidget.setObjectName("Nitrate_Selection_PlotWidget")
                self.View_Culture_Status_TabWidget.addTab(self.tab_4, "")
                self.tab_5 = QtWidgets.QWidget()
                self.tab_5.setObjectName("tab_5")
                self.Ammonium_All_Vessels_Label = QtWidgets.QLabel(self.tab_5)
                self.Ammonium_All_Vessels_Label.setGeometry(QtCore.QRect(300, 250, 101, 16))
                self.Ammonium_All_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Ammonium_All_Vessels_Label.setObjectName("Ammonium_All_Vessels_Label")
                self.Ammonium_Select_Vessels_Dropdown = QtWidgets.QComboBox(self.tab_5)
                self.Ammonium_Select_Vessels_Dropdown.setGeometry(QtCore.QRect(90, 140, 69, 22))
                self.Ammonium_Select_Vessels_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Ammonium_Select_Vessels_Dropdown.setObjectName("Ammonium_Select_Vessels_Dropdown")
                self.Ammonium_Select_Vessels_Label = QtWidgets.QLabel(self.tab_5)
                self.Ammonium_Select_Vessels_Label.setGeometry(QtCore.QRect(60, 90, 131, 16))
                self.Ammonium_Select_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Ammonium_Select_Vessels_Label.setObjectName("Ammonium_Select_Vessels_Label")
                self.Ammonium_Selection_Label = QtWidgets.QLabel(self.tab_5)
                self.Ammonium_Selection_Label.setGeometry(QtCore.QRect(440, 50, 91, 16))
                self.Ammonium_Selection_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Ammonium_Selection_Label.setObjectName("Ammonium_Selection_Label")
                self.Ammonium_All_Vessels_PlotWidget = PlotWidget(self.tab_5)
                self.Ammonium_All_Vessels_PlotWidget.setGeometry(QtCore.QRect(220, 270, 281, 171))
                self.Ammonium_All_Vessels_PlotWidget.setObjectName("Ammonium_All_Vessels_PlotWidget")
                self.Ammonium_Selection_PlotWidget = PlotWidget(self.tab_5)
                self.Ammonium_Selection_PlotWidget.setGeometry(QtCore.QRect(350, 70, 281, 171))
                self.Ammonium_Selection_PlotWidget.setObjectName("Ammonium_Selection_PlotWidget")
                self.View_Culture_Status_TabWidget.addTab(self.tab_5, "")
                self.tab_6 = QtWidgets.QWidget()
                self.tab_6.setObjectName("tab_6")
                self.pH_All_Vessels_Label = QtWidgets.QLabel(self.tab_6)
                self.pH_All_Vessels_Label.setGeometry(QtCore.QRect(300, 250, 101, 16))
                self.pH_All_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.pH_All_Vessels_Label.setObjectName("pH_All_Vessels_Label")
                self.pH_Select_Vessels_Dropdown = QtWidgets.QComboBox(self.tab_6)
                self.pH_Select_Vessels_Dropdown.setGeometry(QtCore.QRect(90, 140, 69, 22))
                self.pH_Select_Vessels_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.pH_Select_Vessels_Dropdown.setObjectName("pH_Select_Vessels_Dropdown")
                self.pH_Select_Vessels_Label = QtWidgets.QLabel(self.tab_6)
                self.pH_Select_Vessels_Label.setGeometry(QtCore.QRect(60, 90, 131, 16))
                self.pH_Select_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.pH_Select_Vessels_Label.setObjectName("pH_Select_Vessels_Label")
                self.pH_Selection_Label = QtWidgets.QLabel(self.tab_6)
                self.pH_Selection_Label.setGeometry(QtCore.QRect(440, 50, 91, 16))
                self.pH_Selection_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.pH_Selection_Label.setObjectName("pH_Selection_Label")
                self.pH_All_Vessels_PlotWidget = PlotWidget(self.tab_6)
                self.pH_All_Vessels_PlotWidget.setGeometry(QtCore.QRect(220, 270, 281, 171))
                self.pH_All_Vessels_PlotWidget.setObjectName("pH_All_Vessels_PlotWidget")
                self.pH_Selection_PlotWidget = PlotWidget(self.tab_6)
                self.pH_Selection_PlotWidget.setGeometry(QtCore.QRect(350, 70, 281, 171))
                self.pH_Selection_PlotWidget.setObjectName("pH_Selection_PlotWidget")
                self.View_Culture_Status_TabWidget.addTab(self.tab_6, "")
                self.tab_2 = QtWidgets.QWidget()
                self.tab_2.setObjectName("tab_2")
                self.DO_All_Vessels_Label = QtWidgets.QLabel(self.tab_2)
                self.DO_All_Vessels_Label.setGeometry(QtCore.QRect(300, 250, 101, 16))
                self.DO_All_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.DO_All_Vessels_Label.setObjectName("DO_All_Vessels_Label")
                self.DO_Select_Vessels_Dropdown = QtWidgets.QComboBox(self.tab_2)
                self.DO_Select_Vessels_Dropdown.setGeometry(QtCore.QRect(90, 140, 69, 22))
                self.DO_Select_Vessels_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.DO_Select_Vessels_Dropdown.setObjectName("DO_Select_Vessels_Dropdown")
                self.DO_Select_Vessels_Label = QtWidgets.QLabel(self.tab_2)
                self.DO_Select_Vessels_Label.setGeometry(QtCore.QRect(60, 90, 131, 16))
                self.DO_Select_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.DO_Select_Vessels_Label.setObjectName("DO_Select_Vessels_Label")
                self.DO_Selection_Label = QtWidgets.QLabel(self.tab_2)
                self.DO_Selection_Label.setGeometry(QtCore.QRect(440, 50, 91, 16))
                self.DO_Selection_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.DO_Selection_Label.setObjectName("DO_Selection_Label")
                self.DO_All_Vessels_PlotWidget = PlotWidget(self.tab_2)
                self.DO_All_Vessels_PlotWidget.setGeometry(QtCore.QRect(220, 270, 281, 171))
                self.DO_All_Vessels_PlotWidget.setObjectName("DO_All_Vessels_PlotWidget")
                self.DO_Selection_PlotWidget = PlotWidget(self.tab_2)
                self.DO_Selection_PlotWidget.setGeometry(QtCore.QRect(350, 70, 281, 171))
                self.DO_Selection_PlotWidget.setObjectName("DO_Selection_PlotWidget")
                self.View_Culture_Status_TabWidget.addTab(self.tab_2, "")
                self.Main_TabWidget.addTab(self.tab_13, "")
                self.tab_14 = QtWidgets.QWidget()
                self.tab_14.setObjectName("tab_14")
                self.Culture_Counts_All_Vessels_Label = QtWidgets.QLabel(self.tab_14)
                self.Culture_Counts_All_Vessels_Label.setGeometry(QtCore.QRect(300, 300, 101, 16))
                self.Culture_Counts_All_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Culture_Counts_All_Vessels_Label.setObjectName("Culture_Counts_All_Vessels_Label")
                self.Culture_Counts_Select_Vessels_Dropdown = QtWidgets.QComboBox(self.tab_14)
                self.Culture_Counts_Select_Vessels_Dropdown.setGeometry(QtCore.QRect(90, 190, 69, 22))
                self.Culture_Counts_Select_Vessels_Dropdown.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.Culture_Counts_Select_Vessels_Dropdown.setObjectName("Culture_Counts_Select_Vessels_Dropdown")
                self.Culture_Counts_Select_Vessels_Label = QtWidgets.QLabel(self.tab_14)
                self.Culture_Counts_Select_Vessels_Label.setGeometry(QtCore.QRect(60, 140, 131, 16))
                self.Culture_Counts_Select_Vessels_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Culture_Counts_Select_Vessels_Label.setObjectName("Culture_Counts_Select_Vessels_Label")
                self.Culture_Counts_Selection_Label = QtWidgets.QLabel(self.tab_14)
                self.Culture_Counts_Selection_Label.setGeometry(QtCore.QRect(440, 100, 91, 16))
                self.Culture_Counts_Selection_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 15pt \"MS Sans Serif\";")
                self.Culture_Counts_Selection_Label.setObjectName("Culture_Counts_Selection_Label")
                self.Culture_Counts_All_Vessels_Chlamy_Label = QtWidgets.QLabel(self.tab_14)
                self.Culture_Counts_All_Vessels_Chlamy_Label.setGeometry(QtCore.QRect(510, 360, 61, 16))
                self.Culture_Counts_All_Vessels_Chlamy_Label.setStyleSheet("color: rgb(0, 170, 0);\n"
        "font: 12pt \"MS Sans Serif\";")
                self.Culture_Counts_All_Vessels_Chlamy_Label.setObjectName("Culture_Counts_All_Vessels_Chlamy_Label")
                self.Culture_Counts_All_Vessels_Yeast_Label = QtWidgets.QLabel(self.tab_14)
                self.Culture_Counts_All_Vessels_Yeast_Label.setGeometry(QtCore.QRect(510, 430, 51, 16))
                self.Culture_Counts_All_Vessels_Yeast_Label.setStyleSheet("color: rgb(255, 255, 0);\n"
        "font: 12pt \"MS Sans Serif\";")
                self.Culture_Counts_All_Vessels_Yeast_Label.setObjectName("Culture_Counts_All_Vessels_Yeast_Label")
                self.Culture_Counts_Selection_Chlamy_Label = QtWidgets.QLabel(self.tab_14)
                self.Culture_Counts_Selection_Chlamy_Label.setGeometry(QtCore.QRect(660, 160, 61, 16))
                self.Culture_Counts_Selection_Chlamy_Label.setStyleSheet("color: rgb(0, 170, 0);\n"
        "font: 12pt \"MS Sans Serif\";")
                self.Culture_Counts_Selection_Chlamy_Label.setObjectName("Culture_Counts_Selection_Chlamy_Label")
                self.Culture_Counts_Selection_Yeast_Label = QtWidgets.QLabel(self.tab_14)
                self.Culture_Counts_Selection_Yeast_Label.setGeometry(QtCore.QRect(660, 240, 51, 16))
                self.Culture_Counts_Selection_Yeast_Label.setStyleSheet("color: rgb(255, 255, 0);\n"
        "font: 12pt \"MS Sans Serif\";")
                self.Culture_Counts_Selection_Yeast_Label.setObjectName("Culture_Counts_Selection_Yeast_Label")
                self.Culture_Counts_Selection_PlotWidget = PlotWidget(self.tab_14)
                self.Culture_Counts_Selection_PlotWidget.setGeometry(QtCore.QRect(340, 130, 281, 171))
                self.Culture_Counts_Selection_PlotWidget.setObjectName("Culture_Counts_Selection_PlotWidget")
                self.Culture_Counts_All_Vessels_PlotWidget = PlotWidget(self.tab_14)
                self.Culture_Counts_All_Vessels_PlotWidget.setGeometry(QtCore.QRect(210, 330, 281, 171))
                self.Culture_Counts_All_Vessels_PlotWidget.setObjectName("Culture_Counts_All_Vessels_PlotWidget")
                self.Main_TabWidget.addTab(self.tab_14, "")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 763, 21))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)
                for i in range(64):
                        self.Glucose_Select_Vessels_Dropdown.addItem("")
                        self.Nitrite_Select_Vessels_Dropdown.addItem("")
                        self.Nitrate_Select_Vessels_Dropdown.addItem("")
                        self.Ammonium_Select_Vessels_Dropdown.addItem("")
                        self.pH_Select_Vessels_Dropdown.addItem("")
                        self.DO_Select_Vessels_Dropdown.addItem("")
                        self.Culture_Counts_Select_Vessels_Dropdown.addItem("")
                self.retranslateUi(MainWindow)
                self.Main_TabWidget.setCurrentIndex(0)
                self.View_Culture_Status_TabWidget.setCurrentIndex(0)
                self.update()
                self.plot()
                
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.Experiment_Parameters_Label.setText(_translate("MainWindow", "Experiment Parameters"))
                self.Experiment_Name_Label.setText(_translate("MainWindow", "Experiment Name:"))
                self.Number_of_Vessels_Label.setText(_translate("MainWindow", "Number of Vessels:"))
                self.Sampling_Frequency_Day_Label.setText(_translate("MainWindow", "Sampling Frequency Day:"))
                self.Glucose_Setpoint_Label.setText(_translate("MainWindow", "Glucose Setpoint (mM):"))
                self.Nitrite_Setpoint_Label.setText(_translate("MainWindow", "Nitrite Setpoint (uM):"))
                self.Glucose_Max_Diff_Label.setText(_translate("MainWindow", "Glucose Max Diff. (mM):"))
                self.Nitrite_Max_Diff_Label.setText(_translate("MainWindow", "Nitrite Max Diff. (uM):"))
                self.Source_Glucose_Concentration_Label.setText(_translate("MainWindow", "Source Glucose Concentration (mM):"))
                self.Source_Nitrite_Concentration_Label.setText(_translate("MainWindow", "Source Nitrite Concentration (mM):"))
                self.Number_of_Vessels_Dropdown.setItemText(0, _translate("MainWindow", "1"))
                self.Number_of_Vessels_Dropdown.setItemText(1, _translate("MainWindow", "2"))
                self.Number_of_Vessels_Dropdown.setItemText(2, _translate("MainWindow", "3"))
                self.Number_of_Vessels_Dropdown.setItemText(3, _translate("MainWindow", "4"))
                self.Number_of_Vessels_Dropdown.setItemText(4, _translate("MainWindow", "5"))
                self.Number_of_Vessels_Dropdown.setItemText(5, _translate("MainWindow", "6"))
                self.Number_of_Vessels_Dropdown.setItemText(6, _translate("MainWindow", "7"))
                self.Number_of_Vessels_Dropdown.setItemText(7, _translate("MainWindow", "8"))
                self.Number_of_Vessels_Dropdown.setItemText(8, _translate("MainWindow", "9"))
                self.Number_of_Vessels_Dropdown.setItemText(9, _translate("MainWindow", "10"))
                self.Number_of_Vessels_Dropdown.setItemText(10, _translate("MainWindow", "11"))
                self.Number_of_Vessels_Dropdown.setItemText(11, _translate("MainWindow", "12"))
                self.Number_of_Vessels_Dropdown.setItemText(12, _translate("MainWindow", "13"))
                self.Number_of_Vessels_Dropdown.setItemText(13, _translate("MainWindow", "14"))
                self.Number_of_Vessels_Dropdown.setItemText(14, _translate("MainWindow", "15"))
                self.Number_of_Vessels_Dropdown.setItemText(15, _translate("MainWindow", "16"))
                self.Number_of_Vessels_Dropdown.setItemText(16, _translate("MainWindow", "17"))
                self.Number_of_Vessels_Dropdown.setItemText(17, _translate("MainWindow", "18"))
                self.Number_of_Vessels_Dropdown.setItemText(18, _translate("MainWindow", "19"))
                self.Number_of_Vessels_Dropdown.setItemText(19, _translate("MainWindow", "20"))
                self.Number_of_Vessels_Dropdown.setItemText(20, _translate("MainWindow", "21"))
                self.Number_of_Vessels_Dropdown.setItemText(21, _translate("MainWindow", "22"))
                self.Number_of_Vessels_Dropdown.setItemText(22, _translate("MainWindow", "23"))
                self.Number_of_Vessels_Dropdown.setItemText(23, _translate("MainWindow", "24"))
                self.Number_of_Vessels_Dropdown.setItemText(24, _translate("MainWindow", "25"))
                self.Number_of_Vessels_Dropdown.setItemText(25, _translate("MainWindow", "26"))
                self.Number_of_Vessels_Dropdown.setItemText(26, _translate("MainWindow", "27"))
                self.Number_of_Vessels_Dropdown.setItemText(27, _translate("MainWindow", "28"))
                self.Number_of_Vessels_Dropdown.setItemText(28, _translate("MainWindow", "29"))
                self.Number_of_Vessels_Dropdown.setItemText(29, _translate("MainWindow", "30"))
                self.Number_of_Vessels_Dropdown.setItemText(30, _translate("MainWindow", "31"))
                self.Number_of_Vessels_Dropdown.setItemText(31, _translate("MainWindow", "32"))
                self.Number_of_Vessels_Dropdown.setItemText(32, _translate("MainWindow", "33"))
                self.Number_of_Vessels_Dropdown.setItemText(33, _translate("MainWindow", "34"))
                self.Number_of_Vessels_Dropdown.setItemText(34, _translate("MainWindow", "35"))
                self.Number_of_Vessels_Dropdown.setItemText(35, _translate("MainWindow", "36"))
                self.Number_of_Vessels_Dropdown.setItemText(36, _translate("MainWindow", "37"))
                self.Number_of_Vessels_Dropdown.setItemText(37, _translate("MainWindow", "38"))
                self.Number_of_Vessels_Dropdown.setItemText(38, _translate("MainWindow", "39"))
                self.Number_of_Vessels_Dropdown.setItemText(39, _translate("MainWindow", "40"))
                self.Number_of_Vessels_Dropdown.setItemText(40, _translate("MainWindow", "41"))
                self.Number_of_Vessels_Dropdown.setItemText(41, _translate("MainWindow", "42"))
                self.Number_of_Vessels_Dropdown.setItemText(42, _translate("MainWindow", "43"))
                self.Number_of_Vessels_Dropdown.setItemText(43, _translate("MainWindow", "44"))
                self.Number_of_Vessels_Dropdown.setItemText(44, _translate("MainWindow", "45"))
                self.Number_of_Vessels_Dropdown.setItemText(45, _translate("MainWindow", "46"))
                self.Number_of_Vessels_Dropdown.setItemText(46, _translate("MainWindow", "47"))
                self.Number_of_Vessels_Dropdown.setItemText(47, _translate("MainWindow", "48"))
                self.Number_of_Vessels_Dropdown.setItemText(48, _translate("MainWindow", "49"))
                self.Number_of_Vessels_Dropdown.setItemText(49, _translate("MainWindow", "50"))
                self.Number_of_Vessels_Dropdown.setItemText(50, _translate("MainWindow", "51"))
                self.Number_of_Vessels_Dropdown.setItemText(51, _translate("MainWindow", "52"))
                self.Number_of_Vessels_Dropdown.setItemText(52, _translate("MainWindow", "53"))
                self.Number_of_Vessels_Dropdown.setItemText(53, _translate("MainWindow", "54"))
                self.Number_of_Vessels_Dropdown.setItemText(54, _translate("MainWindow", "55"))
                self.Number_of_Vessels_Dropdown.setItemText(55, _translate("MainWindow", "56"))
                self.Number_of_Vessels_Dropdown.setItemText(56, _translate("MainWindow", "57"))
                self.Number_of_Vessels_Dropdown.setItemText(57, _translate("MainWindow", "58"))
                self.Number_of_Vessels_Dropdown.setItemText(58, _translate("MainWindow", "59"))
                self.Number_of_Vessels_Dropdown.setItemText(59, _translate("MainWindow", "60"))
                self.Number_of_Vessels_Dropdown.setItemText(60, _translate("MainWindow", "61"))
                self.Number_of_Vessels_Dropdown.setItemText(61, _translate("MainWindow", "62"))
                self.Number_of_Vessels_Dropdown.setItemText(62, _translate("MainWindow", "63"))
                self.Number_of_Vessels_Dropdown.setItemText(63, _translate("MainWindow", "64"))
                self.Start_Experiment_Button.setText(_translate("MainWindow", "Start Experiment"))
                self.End_Experiment_Button.setText(_translate("MainWindow", "End Experiment"))
                self.Assign_COM_Ports_Label.setText(_translate("MainWindow", "Assign COM Ports"))
                self.Libelium_Label.setText(_translate("MainWindow", "Libelium:"))
                self.Nitrite_Label.setText(_translate("MainWindow", "Nitrite:"))
                self.Nitrate_Label.setText(_translate("MainWindow", "Nitrate:"))
                self.Ammonium_Label.setText(_translate("MainWindow", "Ammonium:"))
                self.pH_Label.setText(_translate("MainWindow", "pH:"))
                self.Relays_Label.setText(_translate("MainWindow", "Relays:"))
                self.Delivery_Servos_Label.setText(_translate("MainWindow", "Delivery Servos:"))
                self.Sampling_Servos_Label.setText(_translate("MainWindow", "Sampling Servos:"))
                self.CO2_label.setText(_translate("MainWindow", "CO2:"))
                self.DO_Label.setText(_translate("MainWindow", "DO:"))
                self.Liquid_Flow_Meter_Label.setText(_translate("MainWindow", "Liquid Flow Meter:"))
                self.Cell_Counter_Label.setText(_translate("MainWindow", "Cell Counter:"))
                self.Gas_Flow_Meter_Label.setText(_translate("MainWindow", "Gas Flow Meter:"))
                self.Libelium_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Libelium_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Libelium_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Libelium_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Libelium_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Libelium_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Libelium_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Libelium_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Libelium_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Libelium_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Libelium_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Libelium_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Libelium_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Nitrite_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Nitrite_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Nitrite_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Nitrite_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Nitrite_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Nitrite_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Nitrite_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Nitrite_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Nitrite_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Nitrite_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Nitrite_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Nitrite_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Nitrite_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Nitrate_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Nitrate_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Nitrate_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Nitrate_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Nitrate_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Nitrate_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Nitrate_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Nitrate_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Nitrate_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Nitrate_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Nitrate_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Nitrate_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Nitrate_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Ammonium_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Ammonium_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Ammonium_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Ammonium_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Ammonium_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Ammonium_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Ammonium_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Ammonium_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Ammonium_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Ammonium_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Ammonium_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Ammonium_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Ammonium_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.pH_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.pH_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.pH_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.pH_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.pH_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.pH_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.pH_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.pH_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.pH_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.pH_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.pH_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.pH_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.pH_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Relays_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Relays_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Relays_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Relays_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Relays_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Relays_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Relays_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Relays_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Relays_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Relays_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Relays_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Relays_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Relays_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Delivery_Servos_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Delivery_Servos_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Delivery_Servos_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Delivery_Servos_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Delivery_Servos_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Delivery_Servos_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Delivery_Servos_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Delivery_Servos_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Delivery_Servos_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Delivery_Servos_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Delivery_Servos_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Delivery_Servos_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Delivery_Servos_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Sampling_Servos_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Sampling_Servos_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Sampling_Servos_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Sampling_Servos_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Sampling_Servos_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Sampling_Servos_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Sampling_Servos_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Sampling_Servos_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Sampling_Servos_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Sampling_Servos_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Sampling_Servos_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Sampling_Servos_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Sampling_Servos_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.CO2_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.CO2_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.CO2_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.CO2_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.CO2_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.CO2_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.CO2_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.CO2_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.CO2_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.CO2_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.CO2_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.CO2_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.CO2_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.DO_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.DO_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.DO_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.DO_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.DO_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.DO_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.DO_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.DO_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.DO_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.DO_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.DO_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.DO_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.DO_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Liquid_Flow_Meter_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Cell_Counter_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Cell_Counter_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Cell_Counter_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Cell_Counter_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Cell_Counter_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Cell_Counter_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Cell_Counter_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Cell_Counter_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Cell_Counter_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Cell_Counter_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Cell_Counter_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Cell_Counter_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Cell_Counter_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Gas_Flow_Meter_Dropdown.setItemText(0, _translate("MainWindow", "COM3"))
                self.Gas_Flow_Meter_Dropdown.setItemText(1, _translate("MainWindow", "COM4"))
                self.Gas_Flow_Meter_Dropdown.setItemText(2, _translate("MainWindow", "COM5"))
                self.Gas_Flow_Meter_Dropdown.setItemText(3, _translate("MainWindow", "COM6"))
                self.Gas_Flow_Meter_Dropdown.setItemText(4, _translate("MainWindow", "COM7"))
                self.Gas_Flow_Meter_Dropdown.setItemText(5, _translate("MainWindow", "COM8"))
                self.Gas_Flow_Meter_Dropdown.setItemText(6, _translate("MainWindow", "COM9"))
                self.Gas_Flow_Meter_Dropdown.setItemText(7, _translate("MainWindow", "COM10"))
                self.Gas_Flow_Meter_Dropdown.setItemText(8, _translate("MainWindow", "COM11"))
                self.Gas_Flow_Meter_Dropdown.setItemText(9, _translate("MainWindow", "COM12"))
                self.Gas_Flow_Meter_Dropdown.setItemText(10, _translate("MainWindow", "COM13"))
                self.Gas_Flow_Meter_Dropdown.setItemText(11, _translate("MainWindow", "COM14"))
                self.Gas_Flow_Meter_Dropdown.setItemText(12, _translate("MainWindow", "COM15"))
                self.Main_TabWidget.setTabText(self.Main_TabWidget.indexOf(self.tab_11), _translate("MainWindow", "Experiment Setup"))
                self.CO2_Concentration_Label.setText(_translate("MainWindow", "CO2 Concentration"))
                self.Gas_Flow_Rate_Label.setText(_translate("MainWindow", "Gas Flow Rate"))
                self.Main_TabWidget.setTabText(self.Main_TabWidget.indexOf(self.tab_12), _translate("MainWindow", "Gas Control"))
                self.Glucose_Select_Vessels_Label.setText(_translate("MainWindow", "Select Vessels"))
                self.Glucose_Selection_Label.setText(_translate("MainWindow", "Selection"))
                self.Glucose_All_Vessels_Label.setText(_translate("MainWindow", "All Vessels"))
                self.View_Culture_Status_TabWidget.setTabText(self.View_Culture_Status_TabWidget.indexOf(self.tab), _translate("MainWindow", "Glucose"))
                self.Nitrite_All_Vessels_Label.setText(_translate("MainWindow", "All Vessels"))
                self.Nitrite_Select_Vessels_Label.setText(_translate("MainWindow", "Select Vessels"))
                self.Nitrite_Selection_Label.setText(_translate("MainWindow", "Selection"))
                self.View_Culture_Status_TabWidget.setTabText(self.View_Culture_Status_TabWidget.indexOf(self.tab_3), _translate("MainWindow", "Nitrite"))
                self.Nitrate_All_Vessels_Label.setText(_translate("MainWindow", "All Vessels"))
                self.Nitrate_Select_Vessels_Label.setText(_translate("MainWindow", "Select Vessels"))
                self.Nitrate_Selection_Label.setText(_translate("MainWindow", "Selection"))
                self.View_Culture_Status_TabWidget.setTabText(self.View_Culture_Status_TabWidget.indexOf(self.tab_4), _translate("MainWindow", "Nitrate"))
                self.Ammonium_All_Vessels_Label.setText(_translate("MainWindow", "All Vessels"))
                self.Ammonium_Select_Vessels_Label.setText(_translate("MainWindow", "Select Vessels"))
                self.Ammonium_Selection_Label.setText(_translate("MainWindow", "Selection"))
                self.View_Culture_Status_TabWidget.setTabText(self.View_Culture_Status_TabWidget.indexOf(self.tab_5), _translate("MainWindow", "Ammonium"))
                self.pH_All_Vessels_Label.setText(_translate("MainWindow", "All Vessels"))
                self.pH_Select_Vessels_Label.setText(_translate("MainWindow", "Select Vessels"))
                self.pH_Selection_Label.setText(_translate("MainWindow", "Selection"))
                self.View_Culture_Status_TabWidget.setTabText(self.View_Culture_Status_TabWidget.indexOf(self.tab_6), _translate("MainWindow", "pH"))
                self.DO_All_Vessels_Label.setText(_translate("MainWindow", "All Vessels"))
                self.DO_Select_Vessels_Label.setText(_translate("MainWindow", "Select Vessels"))
                self.DO_Selection_Label.setText(_translate("MainWindow", "Selection"))
                self.View_Culture_Status_TabWidget.setTabText(self.View_Culture_Status_TabWidget.indexOf(self.tab_2), _translate("MainWindow", "DO"))
                self.Main_TabWidget.setTabText(self.Main_TabWidget.indexOf(self.tab_13), _translate("MainWindow", "View Culture Status"))
                self.Culture_Counts_All_Vessels_Label.setText(_translate("MainWindow", "All Vessels"))
                self.Culture_Counts_Select_Vessels_Label.setText(_translate("MainWindow", "Select Vessels"))
                self.Culture_Counts_Selection_Label.setText(_translate("MainWindow", "Selection"))
                self.Culture_Counts_All_Vessels_Chlamy_Label.setText(_translate("MainWindow", "Chlamy"))
                self.Culture_Counts_All_Vessels_Yeast_Label.setText(_translate("MainWindow", "Yeast"))
                self.Culture_Counts_Selection_Chlamy_Label.setText(_translate("MainWindow", "Chlamy"))
                self.Culture_Counts_Selection_Yeast_Label.setText(_translate("MainWindow", "Yeast"))
                self.Main_TabWidget.setTabText(self.Main_TabWidget.indexOf(self.tab_14), _translate("MainWindow", "Culture Counts"))
                count = 0
                for i in vesselArray:
                        self.Culture_Counts_Select_Vessels_Dropdown.setItemText(count, _translate("MainWindow", i))
                        self.Glucose_Select_Vessels_Dropdown.setItemText(count, _translate("MainWindow", i))
                        self.Nitrite_Select_Vessels_Dropdown.setItemText(count, _translate("MainWindow", i))
                        self.Nitrate_Select_Vessels_Dropdown.setItemText(count, _translate("MainWindow", i))
                        self.Ammonium_Select_Vessels_Dropdown.setItemText(count, _translate("MainWindow", i))
                        self.pH_Select_Vessels_Dropdown.setItemText(count, _translate("MainWindow", i))
                        self.DO_Select_Vessels_Dropdown.setItemText(count, _translate("MainWindow", i))
                        count += 1
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
